name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build application
        run: npm run build:all
        env:
          TARGET: ${{ matrix.target }}

      - name: Create release assets
        run: |
          mkdir -p release
          cp src-tauri/target/release/productivity-tracker* release/ || true
          cp CHANGELOG.md release/ || true
          cp RELEASE_NOTES.md release/ || true

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: productivity-tracker-${{ matrix.target }}
          path: release/

  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            productivity-tracker-macos-latest/**/*
            productivity-tracker-ubuntu-latest/**/*
            productivity-tracker-windows-latest/**/*
          body_path: RELEASE_NOTES.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 